bpmdoc/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView
from core.login.views import *
from config import settings as setting
from django.conf.urls.static import static

urlpatterns = [
    path ("", IndexView.as_view(), name='index'),
    path ("login/", include('core.login.urls')),
    path ("admin/", admin.site.urls),
    path ("erp/", include ('core.erp.urls')),
    path ("user/", include ('core.user.urls')),
]

if setting.DEBUG:
    urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

bpmdoc/core/user/urls.py
from django.urls import path
from core.user.views import *

app_name = 'user'

urlpatterns = [
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('profile_ver/', UserProfileConsultView.as_view(), name='user_profile_ver'),
    path('edit/password/', UserChangePasswordView.as_view(), name='change_password'),
    path('register/', registerview, name='account_create')
]

bpmdoc/core/user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import *

from core.user.models import User


class UserForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            form.field.widget.attrs['autocomplete'] = 'off'

    class Meta:
        model = User
        fields = 'first_name', 'last_name', 'email', 'cargo', 'cellphone', 'cedula', 'username', 'password', 'is_active', 'groups'
        widgets = {
            'password': PasswordInput(render_value=True, attrs={'class': 'form-control'}),
            'is_active': NullBooleanSelect(attrs={'class': 'form-control'}),
            'first_name': TextInput(attrs={'class': 'form-control'}),
            'last_name': TextInput(attrs={'class': 'form-control'}),
            'email': EmailInput(attrs={'class': 'form-control', 'required': True}),
            'cargo': TextInput(attrs={'class': 'form-control'}),
            'cellphone': TextInput(attrs={'class': 'form-control'}),
            'cedula': TextInput(attrs={'class': 'form-control'}),
            'username': TextInput(attrs={'class': 'form-control'}),
            'groups': SelectMultiple(attrs={'class': 'form-control'})
        }
        exclude = ['user_permissions', 'last_login', 'date_joined', 'is_superuser', 'is_staff']

    def save(self, commit=True):
        data ={}
        form = super()
        try:
            if form.is_valid():
                pwd = self.cleaned_data['password']
                u = form.save(commit=False)
                if u.pk is None:
                    u.set_password(pwd)
                else:
                    user = User.objects.get(pk=u.pk)
                    if user.password != pwd:
                        u.set_password (pwd)
                u.save()
                u.groups.clear()
                for g in self.cleaned_data['groups']:
                    u.groups.add(g)
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data

class UserProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            form.field.widget.attrs['autocomplete'] = 'off'

    class Meta:
        model = User
        fields = 'first_name', 'last_name', 'email', 'cargo', 'cellphone', 'cedula', 'username'
        widgets = {
            'first_name': TextInput(attrs={'class': 'form-control'}),
            'last_name': TextInput(attrs={'class': 'form-control'}),
            'email': EmailInput(attrs={'class': 'form-control', 'readonly': True}),
            'cargo': TextInput(attrs={'class': 'form-control'}),
            'cellphone': TextInput(attrs={'class': 'form-control'}),
            'cedula': TextInput(attrs={'class': 'form-control'}),
            'username': TextInput(attrs={'class': 'form-control', 'readonly': True}),
        }
        exclude = ['user_permissions', 'last_login', 'date_joined', 'is_superuser', 'is_staff', 'groups', 'is_active', 'password']

    def save(self, commit=True):
        data ={}
        form = super()
        try:
            if form.is_valid():
                pwd = self.cleaned_data['password']
                u = form.save(commit=False)
                if u.pk is None:
                    u.set_password(pwd)
                else:
                    user = User.objects.get(pk=u.pk)
                    if user.password != pwd:
                        u.set_password (pwd)
                u.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data


class UserProfileConsultForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for form in self.visible_fields():
            form.field.widget.attrs['autocomplete'] = 'off'

    class Meta:
        model = User
        fields = 'first_name', 'last_name', 'email', 'cargo', 'cellphone', 'cedula', 'username'
        widgets = {
            'first_name': TextInput(attrs={'class': 'form-control', 'readonly': True}),
            'last_name': TextInput(attrs={'class': 'form-control', 'readonly': True}),
            'email': EmailInput(attrs={'class': 'form-control', 'readonly': True}),
            'cargo': TextInput(attrs={'class': 'form-control', 'readonly': True}),
            'cellphone': TextInput(attrs={'class': 'form-control', 'readonly': True}),
            'cedula': TextInput(attrs={'class': 'form-control', 'readonly': True}),
            'username': TextInput(attrs={'class': 'form-control', 'readonly': True}),
        }
        exclude = ['user_permissions', 'last_login', 'date_joined', 'is_superuser', 'is_staff', 'groups', 'is_active', 'password']

    def save(self, commit=True):
        data ={}
        form = super()
        try:
            if form.is_valid():
                pwd = self.cleaned_data['password']
                u = form.save(commit=False)
                if u.pk is None:
                    u.set_password(pwd)
                else:
                    user = User.objects.get(pk=u.pk)
                    if user.password != pwd:
                        u.set_password (pwd)
                u.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data

class RegisterForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2', 'groups')
        exclude = ['user_permissions', 'last_login', 'date_joined', 'is_superuser', 'is_staff', 'is_active', 'cellphone',
                   'cedula', 'first_name', 'last_name', 'cargo']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

bpmdoc/core/user/views.py
from datetime import datetime

from django.contrib.auth import update_session_auth_hash, login
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect

from core.erp.mixins import ValidatePermissionRequiredMixin
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, FormView

from core.erp.models import Document
from core.user.forms import UserForm, UserProfileForm, UserProfileConsultForm, RegisterForm
from core.user.models import User


class UserListView(LoginRequiredMixin, ValidatePermissionRequiredMixin, ListView):
    model = User
    template_name = 'user/list.html'
    permission_required = 'user.view_user'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in User.objects.filter(is_superuser=False).order_by('first_name'):
                    data.append(i.tojson())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tittle'] = 'Usuarios'
        context['create_url'] = reverse_lazy('user:user_create')
        context['list_url'] = reverse_lazy('user:user_list')
        context['count_vencido'] = Document.objects.filter(status='Vencido').filter(
            owner=self.request.user).count()
        context['count_aprobar'] = Document.objects.filter(status='En Aprobación').filter(
            owner=self.request.user).count()
        context['count_elaboracion'] = Document.objects.filter(status='En Elaboración').filter(
            creator=self.request.user).count()
        context['count_revisar'] = Document.objects.filter(status='En Revisión').filter(
            reviewer=self.request.user).count()
        context['count_por_vencer'] = Document.objects.filter(status='Vigente').filter(
            date_alert_exp__lte=datetime.now()).filter(owner=self.request.user).count()
        context['count_total'] = context['count_aprobar'] + context['count_vencido'] + context['count_elaboracion'] + \
                                 context['count_revisar'] + context['count_por_vencer']
        context['entity'] = 'Usuarios'
        return context


class UserCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = User
    form_class = UserForm
    template_name = 'user/create.html'
    success_url = reverse_lazy('user:user_list')
    permission_required = 'user.add_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        global form
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    data = form.save()
                    name_username = form.cleaned_data.get ('username')
                    messages.success (request, F'Usuario {name_username} creado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tittle'] = 'Creación de Usuarios'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        context['count_vencido'] = Document.objects.filter(status='Vencido').filter(
            owner=self.request.user).count()
        context['count_aprobar'] = Document.objects.filter(status='En Aprobación').filter(
            owner=self.request.user).count()
        context['count_elaboracion'] = Document.objects.filter(status='En Elaboración').filter(
            creator=self.request.user).count()
        context['count_revisar'] = Document.objects.filter(status='En Revisión').filter(
            reviewer=self.request.user).count()
        context['count_por_vencer'] = Document.objects.filter(status='Vigente').filter(
            date_alert_exp__lte=datetime.now()).filter(owner=self.request.user).count()
        context['count_total'] = context['count_aprobar'] + context['count_vencido'] + context['count_elaboracion'] + \
                                 context['count_revisar'] + context['count_por_vencer']
        context['entity'] = 'Crear Usuario'
        return context


class UserUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserForm
    template_name = 'user/create.html'
    success_url = reverse_lazy('user:user_list')
    permission_required = 'user.change_user'
    url_redirect = success_url

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        global form
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    data = form.save()
                    name_username = form.cleaned_data.get ('username')
                    messages.success (request, f'Usuario {name_username} actualizado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tittle'] = 'Edición de Usuarios'
        context['list_url'] = self.success_url
        context['entity'] = 'Editar de Usuario'
        context['count_vencido'] = Document.objects.filter(status='Vencido').filter(
            owner=self.request.user).count()
        context['count_aprobar'] = Document.objects.filter(status='En Aprobación').filter(
            owner=self.request.user).count()
        context['count_elaboracion'] = Document.objects.filter(status='En Elaboración').filter(
            creator=self.request.user).count()
        context['count_revisar'] = Document.objects.filter(status='En Revisión').filter(
            reviewer=self.request.user).count()
        context['count_por_vencer'] = Document.objects.filter(status='Vigente').filter(
            date_alert_exp__lte=datetime.now()).filter(owner=self.request.user).count()
        context['count_total'] = context['count_aprobar'] + context['count_vencido'] + context['count_elaboracion'] + \
                                 context['count_revisar'] + context['count_por_vencer']
        context['action'] = 'edit'
        return context


class UserProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'user/profile.html'
    success_url = reverse_lazy('user:user_profile_ver')

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        return self.request.user

    def post(self, request, *args, **kwargs):
        global form
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    data = form.save()
                    name_username = form.cleaned_data.get ('username')
                    messages.success (request, f'Usuario "{name_username}", editado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tittle'] = 'Edición de Perfil'
        context['list_url'] = self.success_url
        context['entity'] = 'Editar Perfil'
        context['count_vencido'] = Document.objects.filter(status='Vencido').filter(
            owner=self.request.user).count()
        context['count_aprobar'] = Document.objects.filter(status='En Aprobación').filter(
            owner=self.request.user).count()
        context['count_elaboracion'] = Document.objects.filter(status='En Elaboración').filter(
            creator=self.request.user).count()
        context['count_revisar'] = Document.objects.filter(status='En Revisión').filter(
            reviewer=self.request.user).count()
        context['count_por_vencer'] = Document.objects.filter(status='Vigente').filter(
            date_alert_exp__lte=datetime.now()).filter(owner=self.request.user).count()

bpmdoc/core/user/templates/user/change_password.html
{% extends 'body.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="justify-content-center col-lg-10">
        <form method="post" action="" enctype="multipart/form-data" class="form-group">
            <div class="card">
                <!--Título de la tabla -->
                <div class="card shadow mb-4">
                    <span class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary" style="text-transform: uppercase">
                            <i class="fas fa-user-edit"></i>
                            {{ entity }}
                        </h6>
                    </span>
                </div>
                <div class="container-fluid">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="{{ action }}">
                    <div class="alert alert-danger bg-gradient-danger text-white alert-dismissible errormsg col-lg-7"
                         style="display: none; border-radius: 5px;">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Error en el Registro!</h5>
                        <div class="errors"></div>
                    </div>

                    {% if form.errors %}
                        <div class="px-3 py-3 bg-gradient-danger text-white" style="border-radius: 5px;">
                            <ul>
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    {% for field in form.visible_fields %}
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="email">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="card-footer">
                      <button type="submit" class="btn btn-primary">
                        <span class="icon text-white-50">
                          <i class="fas fa-check"></i>
                        </span>
                        <span class="text"> Guardar</span>
                      </button>
                      <a href="{{ inicio_url }}" class="btn btn-secondary">
                          <span class="icon text-white-50">
                              <i class="fa fa-times"></i>
                          </span>
                          <span class="text"> Cancelar</span>
                      </a>
                    </div>
                </div>
        </form>
    </div>
    <script>
        $('form').on('submit', function(e){
            e.preventDefault();
            var parameters = new FormData(this);
            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: parameters,
                dataType: 'json',
                processData: false,
                contentType: false,
            }).done(function (data) {
                console.log(data);
                if (!data.hasOwnProperty('error')) {
                    location.href = '{{ list_url }}';
                    return false;
                }
                message_error(data.error);
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function (data) {
            });
        });

    </script>
{% endblock %}

bpmdoc/core/user/templates/user/create.html
{% extends 'form.html' %}

bpmdoc/core/user/templates/user/detail.html
{% extends 'body.html' %}
{% load static %}
{% block head %}

  <!-- Custom styles for this page -->
  <link href="{% static 'lib/startbootstrap-sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

{% endblock %}

{% block content %}

    <!-- DataTale List -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
         <h6 class="m-0 font-weight-bold text-primary" style="text-transform: uppercase"><i class="fas fa-fw fa-table"></i> {{ object.get_full_name }}</h6>
      </div>
          <div class="card-body">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-4">
                                    <p class="card-text"><strong>Nombre de Usuario:</strong></p>{{ object.username }}
                                </div>
                                <div class="col-md-4">
                                    <p class="card-text"><strong>Email:</strong></p>{{ object.email }}
                                </div>
                                <div class="col-md-4">
                                    <p class="card-text"><strong>Cargo:</strong></p>{{ object.cargo }}
                                </div>
                                <div class="col-md-4">
                                    <p class="card-text"><strong>N° Celular:</strong></p>{{ object.cellphone }}
                                </div>
                                <div class="col-md-4">
                                    <p class="card-text"><strong>Cedula:</strong></p>{{ object.cedula }}
                                </div>
                            </div>
                        </div>
                    </div>
          </div>
                <div class="card-footer">
                  <a href="{% url 'user:user_profile' %}" class="btn btn-primary">
                    <span class="icon text-white-50">
                      <i class="fas fa-check"></i>
                    </span>
                    <span class="text"> Editar Perfil</span>
                  </a>
                     <a href="{{ list_url }}" class="btn btn-secondary">
                        <span class="icon text-white-50">
                          <i class="fa fa-times"></i>
                        </span>
                        <span class="text">Cerrar</span>
                     </a>
                </div>

    </div>

{% endblock %}

bpmdoc/core/user/templates/user/list.html
{% extends 'list.html' %}
{% load static %}

{% block head_list %}
    <script src="{% static 'user/js/list.js' %}"></script>
{% endblock %}

{% block columns %}
    <th class="text-md-center" style="width:5%"></th>
    <th class="text-md-center" style="width:25%">Nombre Completo</th>
    <th class="text-md-center" style="width:10%">Username</th>
    <th class="text-md-center" style="width:20%">Cargo</th>
    <th class="text-md-center" style="width:10%">Roles</th>
    <th class="text-md-center" style="width:20%">Email</th>
    <th class="text-md-center" style="width:5%">Activo</th>
    <th class="text-md-center" style="width:5%">Acciones</th>
{% endblock %}

{% block rows %}

{% endblock %}

{% block javascript %}


{% endblock %}

bpmdoc/core/user/templates/user/profile.html
{% extends 'form.html' %}

bpmdoc/core/user/templates/user/verprofile.html
{% extends 'body.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="justify-content-center col-lg-10">
        <form method="post" action="" enctype="multipart/form-data" class="form-group">
            <div class="card">
                <!--Título de la tabla -->
                <div class="card shadow mb-4">
                    <span class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary" style="text-transform: uppercase">
                            <i class="fas fa-user"></i>
                            {{ entity }}
                        </h6>
                    </span>
                </div>
                <div class="container-fluid">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="{{ action }}">
                    <div class="alert alert-danger bg-gradient-danger text-white alert-dismissible errormsg col-lg-7"
                         style="display: none; border-radius: 5px;">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Error en el Registro!</h5>
                        <div class="errors"></div>
                    </div>

                    {% if form.errors %}
                        <div class="px-3 py-3 bg-gradient-danger text-white" style="border-radius: 5px;">
                            <ul>
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    {% for field in form.visible_fields %}
                        {% if forloop.first %}
                            <div class="row">
                        {% endif %}
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="email">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    </div>
                    {% if forloop.last %}
                        </div>
                    {% elif forloop.counter|divisibleby:2 %}
                        </div>
                        <div class="row">
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="card-footer">
                    <a href="{% url 'user:user_profile' %}" class="btn btn-primary bg-gradient-primary text-white"> Editar Perfil</a>
                    <a href="{{ list_url }}" class="btn btn-danger bg-gradient-danger text-white">Cerrar</a>
                </div>
            </div>
        </form>
    </div>
    <script>
        $('form').on('submit', function(e){
            e.preventDefault();
            var parameters = new FormData(this);
            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: parameters,
                dataType: 'json',
                processData: false,
                contentType: false,
            }).done(function (data) {
                console.log(data);
                if (!data.hasOwnProperty('error')) {
                    location.href = '{{ list_url }}';
                    return false;
                }
                message_error(data.error);
            }).fail(function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function (data) {
            });
        });

    </script>
{% endblock %}