bpmdoc/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView
from core.login.views import *
from config import settings as setting
from django.conf.urls.static import static

urlpatterns = [
    path ("", IndexView.as_view(), name='index'),
    path ("login/", include('core.login.urls')),
    path ("admin/", admin.site.urls),
    path ("erp/", include ('core.erp.urls')),
    path ("user/", include ('core.user.urls')),
]

if setting.DEBUG:
    urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

bpmdoc/core/erp/urls.py
from django.urls import path

from core.erp.views.changes.views import *
from core.erp.views.inicio.views import *
from core.erp.views.process.views import *
from core.erp.views.typedoc.views import *
from core.erp.views.docs.views import *
from core.homepage.views import SinpermisosView

# url media files
from django.conf import settings
from django.conf.urls.static import static


app_name = 'erp'

urlpatterns = [
    # Tipos de documento
    path('typedoc/list/', TypedocListView.as_view(), name='typedoc_list'),
    path("typedoc/add/", TypeCreateView.as_view(), name='type_create'),
    path('typedoc/update/<int:pk>/', TypeUpdateView.as_view(), name='type_update'),
    path('typedoc/delete/<int:pk>/', TypeDeleteView.as_view(), name='type_delete'),
    path('typedoc/form/', TypeFormView.as_view(), name='type_form'),

    # Documentos
    path('docs/list/', DocListView.as_view(), name='docs_list'),
    path('docs/review_list/', DocRevListView.as_view(), name='docs_review_list'),
    path('docs/approve_list/', DocAproListView.as_view(), name='docs_aprove_list'),
    path('docs/created_list/', DocCreatedListView.as_view(), name='docs_created_list'),
    path('docs/gestion_list/', DocGestListView.as_view(), name='docs_gest_list'),
    path('docs/adjust_update/<int:pk>/', DocAdjustUpdateView.as_view(), name='docs_adjust_update'),
    path('docs/review_update/<int:pk>/', DocRevUpdateView.as_view(), name='docs_review_update'),
    path('docs/approve_update/<int:pk>/', DocAproUpdateView.as_view(), name='docs_aprove_update'),
    path('docs/devolut_update/<int:pk>/', DocDevUpdateView.as_view(), name='docs_devolut_update'),
    path('docs/consulta/', ConsulDocListView.as_view(), name='consultdocs_list'),
    path('docs/add/', DocCreateView.as_view(), name='docs_create'),
    path('docs/update/<int:pk>/', DocUpdateView.as_view(), name='docs_update'),
    path('docs/delete/<int:pk>/', DocDeleteView.as_view(), name='docs_delete'),
    path('docs/detail/<int:pk>', DocsDetailView.as_view(), name='docs_detail'),
    path('docs/form/', DocFormView.as_view(), name='docs_form'),
    path('docs/listado_maestros_docs/', ReportDocsExcel.as_view(), name='list_master_docs'),

    # Procesos
    path('process/list/', ProcessListView.as_view(), name='process_list'),
    path('process/add/', ProcessCreateView.as_view(), name='process_create'),
    path('process/update/<int:pk>/', ProcessUpdateView.as_view(), name='process_update'),
    path('process/delete/<int:pk>/', ProcessDeleteView.as_view(), name='process_delete'),
    path('process/form/', ProcessFormView.as_view(), name='process_form'),

    # Cambios de documentos/ Control de Cambios
    path('changes/update/<int:id_change>/', document_change, name='changes_control'),

    # Inicio
    path('inicio/', InicioView.as_view(), name='inicio'),
    path('inicio/sinpermisos/', SinpermisosView.as_view(), name='sinpermisos'),

]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

bpmdoc/core/erp/models.py
from crum import get_current_user
from django.core.validators import FileExtensionValidator

from django.db import models
from django.forms import model_to_dict
from simple_history.models import HistoricalRecords

from core.models import BaseModel
from djchoices import ChoiceItem, DjangoChoices
from config.settings import MEDIA_URL
from core.user.models import User
from datetime import datetime, timedelta


class Type(BaseModel):
    typedoc = models.CharField(max_length=60, verbose_name='Descripción', unique=True)
    codetype = models.CharField(max_length=10, verbose_name='Código', unique=True)
    validity = models.IntegerField(verbose_name='Años de Vigencia')
    history = HistoricalRecords(custom_model_name=lambda x:f'Audit_{x}')

    def __str__(self):
        return self.typedoc

    def toJSON(self):
        item = model_to_dict(self)
        item['user_creation'] = self.user_creation.__str__()
        item['user_updated'] = self.user_updated.__str__()
        item['date_creation'] = self.date_creation.strftime('%Y-%m-%d')
        item['date_updated'] = self.date_updated.strftime('%Y-%m-%d')
        return item

    class Meta:
        db_table = 'Tipo_Documento'
        verbose_name = 'Tipo de Documento'
        verbose_name_plural = 'Tipos de Documentos'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None, *args, **kwargs):
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        self.typedoc = self.typedoc.capitalize()
        self.codetype = self.codetype.upper()
        return super(Type, self).save(*args, **kwargs)


class VigenciaDoc(DjangoChoices):
    one_year = ChoiceItem('365', "1 año")
    two_year = ChoiceItem('730', "2 años")
    three_year = ChoiceItem('1095', "3 años")
    four_year = ChoiceItem('1461', "4 años")
    five_year = ChoiceItem('1825', "5 años")


class StatusDoc(DjangoChoices):
    elaboracion = ChoiceItem('En Elaboración', "En Elaboración")
    revision = ChoiceItem("En Revisión", "En Revisión")
    aprobacion = ChoiceItem("En Aprobación", "En Aprobación")
    aprobado = ChoiceItem("Aprobado", "Aprobado")
    vigente = ChoiceItem("Vigente", "Vigente")
    vencido = ChoiceItem("Vencido", "Vencido")
    obsoleto = ChoiceItem("Obsoleto", "Obsoleto")
    prueba = ChoiceItem("En Prueba", "En Prueba")
    anulado = ChoiceItem("Anulado", "Anulado")


class Document(BaseModel):
    code = models.CharField(max_length=15, verbose_name='Código')
    description = models.CharField(max_length=200, verbose_name='Descripción')
    version = models.IntegerField(default=1, verbose_name='Versión N°')
    tipodoc = models.ForeignKey('Type', verbose_name='Tipo de Documento', on_delete=models.CASCADE)
    creator = models.ForeignKey(User, blank=False, verbose_name='Creado por', on_delete=models.CASCADE,
                                related_name='+')
    reviewer = models.ForeignKey(User, blank=False, verbose_name='Revisado por', on_delete=models.CASCADE,
                                 related_name='+')
    owner = models.ForeignKey(User, blank=False, verbose_name='Aprobado por', on_delete=models.CASCADE,
                              related_name='+')
    proceso = models.ForeignKey('Process', verbose_name='Proceso', on_delete=models.CASCADE)
    filepdf = models.FileField(upload_to='docspdf/%Y/%m/%d', max_length=200, blank=True,
                               verbose_name='Documento en PDF', validators=[FileExtensionValidator(['pdf'])])
    fileword = models.FileField(upload_to='docsword/%Y/%m/%d', max_length=200, blank=True,
                                verbose_name='Documento editable', validators=[FileExtensionValidator(['xls', 'xlsx', 'doc', 'docx'])])
    anexo = models.FileField(upload_to='anexos/%Y/%m/%d', max_length=200, blank=True, null=True, verbose_name='Anexo 1')
    anexo_dos = models.FileField(upload_to='anexos_dos/%Y/%m/%d', max_length=200, blank=True, null=True,
                                 verbose_name='Anexo 2')
    status = models.CharField(max_length=100, default='En Elaboración', choices=StatusDoc.choices,
                              verbose_name='Estado')
    changes = models.CharField(max_length=1000, null=True, blank=True, verbose_name='Cambios Realizados')
    justification = models.CharField(max_length=1000, null=True, blank=True, verbose_name='Justificación del Cambio')
    numberchange = models.IntegerField(unique=True, null=True, blank=True, verbose_name='N° de Documento')
    review = models.BooleanField(default=False, null=True, blank=True, verbose_name='Aprobar Revisión')
    approval = models.BooleanField(default=False, null=True, blank=True, verbose_name='Aprobar Documento')
    date_revised = models.DateField(default=None, blank=True, null=True, verbose_name='Fecha de Revisado')
    date_approved = models.DateField(default=None, blank=True, null=True, verbose_name='Fecha de Aprobado')
    time_vigencia = models.CharField(max_length=10, choices=VigenciaDoc.choices, blank=True, null=True,
                                     verbose_name='Tiempo de Vigencia')
    date_vigencia = models.DateField(default=None, blank=True, null=True, verbose_name='Vencimiento de Documento')
    date_alert_exp = models.DateField(default=None, blank=True, null=True, verbose_name='Fecha Notificacion Proximo a Vencer')
    comment_review = models.CharField(max_length=250, null=True, blank=True, verbose_name='Observaciones Revisión')
    comment_aprove = models.CharField(max_length=250, null=True, blank=True, verbose_name='Observaciones Aprobación')
    empresa = models.CharField(max_length=50, default='Laboratorios H&B SAS', verbose_name='Compañia', null=True, blank=True)
    history = HistoricalRecords(custom_model_name=lambda x:f'Audit_{x}')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.last_name = None
        self.first_name = None

    def __str__(self):
        return self.description

    def toJSON(self):
        item = model_to_dict(self)
        item['tipodoc'] = self.tipodoc.toJSON()
        item['proceso'] = self.proceso.toJSON()
        item['filepdf'] = self.get_pdf()
        item['fileword'] = self.get_status_display()
        item['anexo'] = self.get_status_anexo()
        item['anexo_dos'] = self.get_status_anexo_dos()
        item["date_vigencia"] = None if self.date_vigencia is None else self.date_vigencia.strftime('%Y-%m-%d')
        item['date_alert_exp'] = None if self.date_alert_exp is None else self.date_alert_exp.strftime('%Y-%m-%d')
        item['date_creation'] = self.date_creation.strftime('%Y-%m-%d')
        item['date_updated'] = self.date_updated.strftime('%Y-%m-%d')
        item["date_revised"] = None if self.date_revised is None else self.date_revised.strftime('%Y-%m-%d')
        item['date_approved'] = None if self.date_approved is None else self.date_approved.strftime('%Y-%m-%d')
        return item

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None, *args, **kwargs):
        if self.date_approved is not None:
            diasv = self.time_vigencia
            intdiasv = int(diasv)
            self.date_vigencia = datetime.now() + timedelta(days=intdiasv)
        if self.date_vigencia is not None:
            self.date_alert_exp = self.date_vigencia - timedelta(days=30)
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        super(Document, self).save()
        self.description = self.description.capitalize()
        self.code = self.code.upper()
        return super(Document, self).save(*args, **kwargs)

    def get_pdf(self):
        if self.filepdf:
            return '{}{}'.format(MEDIA_URL, self.filepdf)
        return ''

    def get_status_display(self):
        if self.fileword:
            return '{}{}'.format(MEDIA_URL, self.fileword)
        return ''

    def get_status_anexo(self):
        if self.anexo:
            return '{}{}'.format(MEDIA_URL, self.anexo)
        return ''

    def get_status_anexo_dos(self):
        if self.anexo_dos:
            return '{}{}'.format(MEDIA_URL, self.anexo_dos)
        return ''

    class Meta:
        verbose_name = 'Documento'
        verbose_name_plural = 'Documentos'
        db_table = 'Documentos'
        ordering = ['-date_updated']


class Process(BaseModel):
    process = models.CharField(max_length=60, verbose_name='Descripción', unique=True)
    codeprocess = models.CharField(max_length=10, verbose_name='Código', unique=True)
    leader = models.ForeignKey(User, blank=True, verbose_name='Líder de Proceso', on_delete=models.CASCADE)
    history = HistoricalRecords(custom_model_name=lambda x:f'Audit_{x}')

    def __str__(self):
        return self.process

    def toJSON(self):
        item = model_to_dict(self)
        item['leader'] = self.leader.tojson()
        return item

    class Meta:
        db_table = 'Proceso'
        verbose_name = 'Proceso'
        verbose_name_plural = 'Procesos'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None, *args, **kwargs):
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        self.process = self.process.capitalize()
        self.codeprocess = self.codeprocess.upper()
        return super(Process, self).save(*args, **kwargs)

bpmdoc/core/erp/views/changes/views.py
from datetime import datetime
from random import randint

from django.contrib import messages
from django.shortcuts import redirect, render

from core.erp.models import Document
from core.erp.forms import ChangeForms



def document_change(request, id_change):
    document = Document.objects.get(id=id_change)
    document.id = None
    document.filepdf = None
    document.anexo = None
    document.anexo_dos = None
    document.justification = None
    document.approval= False
    document.review = False
    document.comment_aprove = None
    document.comment_review = None
    document.date_revised = datetime.now()
    document.changes = None
    document.status = 'En Revisión'
    document.creator = request.user
    document.version += 1
    consecutivo_numberdoc = numberchangerandom(5)
    document.numberchange = consecutivo_numberdoc
    if request.method == 'GET':
        form = ChangeForms(instance=document)
    else:
        version = request.POST.get('version')
        document.version = version
        changes = request.POST.get('changes')
        document.changes = changes
        justification = request.POST.get('justification')
        document.justification = justification
        numberchange = request.POST.get('numberchange')
        document.numberchange = numberchange
        document.save()
        messages.success (request, f'Cambio del documento "{document.code} {document.description}" enviado a ruta de aprobación!')
        return redirect('erp:docs_gest_list')

    context = {
        'form': form,
        'count_aprobar': Document.objects.filter(status='En Aprobación').filter(owner=request.user).count(),
        'count_elaboracion': Document.objects.filter(status='En Elaboración').filter(creator=request.user).count(),
        'count_revisar': Document.objects.filter(status='En Revisión').filter(reviewer=request.user).count(),
        'count_vencido': Document.objects.filter(status='Vencido').filter(owner=request.user).count(),
        'count_por_vencer': Document.objects.filter(status='Vigente').filter(
            date_alert_exp__lte=datetime.now()).filter(owner=request.user).count(),
        'count_total': 'count_aprobar' + 'count_vencido' + 'count_elaboracion' + 'count_revisar' + 'count_por_vencer'
    }
    return render(request, 'changes/create.html', context)


def numberchangerandom(n):
    range_start = 10**(n-1)
    range_end = (10**n)-1
    numbase = 10**n
    return numbase+randint(range_start, range_end)

bpmdoc/core/erp/views/inicio/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from core.erp.models import Document


class InicioView(LoginRequiredMixin, TemplateView):
    template_name = 'inicio.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'panel del administrador'
        context['tittle'] = 'Inicio'
        context['entity'] = 'Inicio'
        context['count_vencido'] = Document.objects.filter(status='Vencido').filter(
            owner=self.request.user).count()
        context['count_aprobar'] = Document.objects.filter(status='En Aprobación').filter(
            owner=self.request.user).count()
        context['count_elaboracion'] = Document.objects.filter(status='En Elaboración').filter(
            creator=self.request.user).count()
        context['count_revisar'] = Document.objects.filter(status='En Revisión').filter(
            reviewer=self.request.user).count()
        context['count_por_vencer'] = Document.objects.filter(status='Vigente').filter(
            date_alert_exp__lte=datetime.now()).filter(owner=self.request.user).count()
        context['count_total'] = context['count_aprobar'] + context['count_vencido'] + context['count_elaboracion'] + \
                                 context['count_revisar'] + context['count_por_vencer']
        return context

bpmdoc/core/erp/templates/docs/create.html
{% extends 'form.html' %}

bpmdoc/core/erp/templates/docs/create_modal.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h2 class="modal-title">Edición de Libro: </h2>
            <button class="close" type="button" data-dismiss = "modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form id="edicion"  action="{% url 'erp:docs_devolut_update' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-body">
                <div id="erroresEdicion">

                </div>
                {{ form.as_p }}
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" type="button" onclick="cerrar_modal_edicion();">Cancelar</button>
                <button id="boton_creacion" class="btn btn-primary" type="button" onclick="editar();">Confirmar</button>
            </div>
        </form>
    </div>
</div>

bpmdoc/core/erp/templates/docs/delete.html
{% extends 'delete.html' %}

bpmdoc/core/erp/templates/docs/detail.html
{% extends 'body.html' %}
{% load static %}
{% block head %}

  <!-- Custom styles for this page -->
  <link href="{% static 'lib/startbootstrap-sb-admin-2/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

{% endblock %}

{% block content %}

    <!-- DataTale List -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
         <h6 class="m-0 font-weight-bold text-primary" style="text-transform: uppercase"><i class="far fa-file-alt fa-lg"></i> {{ object.code }} {{ object.description }}. Versión: {{ object.version }}</h6>
      </div>
      <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <p class="card-text"><strong>Elaborado por:</strong></p>{{ object.creator }}
            </div>
            <div class="col-md-4">
                <p class="card-text"><strong>Revisado por:</strong></p>{{ object.reviewer }}
            </div>
            <div class="col-md-4">
                <p class="card-text"><strong>Aprobado por:</strong></p>{{ object.owner }}
            </div>
        </div>
      </div>
      <div class="card-body">
          <div class="row">
            <div class="col-md-4">
                <p class="card-text"><strong>Fecha de Elaborado:</strong></p>{{ object.date_creation }}
            </div>
            <div class="col-md-4">
                <p class="card-text"><strong>Fecha de Revisado:</strong></p>{{ object.date_revised }}
            </div>
            <div class="col-md-4">
                <p class="card-text"><strong>Fecha de Aprobado:</strong></p>{{ object.date_approved }}
            </div>
          </div>
      </div>
      <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <p class="card-text"><strong>Fecha de Vigencia:</strong></p>{{ object.date_vigencia }}
            </div>
            <div class="col-md-4">
                <p class="card-text"><strong>N° de Documento:</strong></p>{{ object.numberchange }}
            </div>
          </div>
      </div>

      <div class="card-body">
          <div class="row">
            <div class="col-md-4">
                <p class="card-text"><strong>Cambios Realizados:</strong></p>{{ object.changes }}
            </div>
            <div class="col-md-4">
                <p class="card-text"><strong>Justificación del Cambio:</strong></p>{{ object.justification }}
            </div>
          </div>
      </div>


            <div class="card-footer">
                {% if perms.erp.add_document %}
                     <a href="{{ list_url }}" class="btn btn-primary text-white" type="submit">Volver al Listado</a>
                {% elif perms.erp.change_document %}
                     <a href="{% url 'erp:docs_gest_list' %}" class="btn btn-primary text-white" type="submit">Volver al Listado</a>
                {% endif %}
                {% if not perms.erp.change_document %}
                     <a href="{% url 'erp:consultdocs_list' %}" class="btn btn-primary text-white" type="submit">Volver al Listado</a>
                {% endif %}

            </div>
        </div>




{% endblock %}

{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false,
                language: {
                url: "//cdn.datatables.net/plug-ins/1.10.21/i18n/Spanish.json"
            },
            });

            $('.btnTest').on('click', function () {
                $.ajax({
                    url: window.location.pathname,
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function (data) {
                    console.log(data);
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                }).always(function (data) {

                });
            });
        });
    </script>
{% endblock %}

bpmdoc/core/erp/templates/docs/list.html
{% extends 'list.html' %}
{% load static %}

{% block head_list %}
    <script src="{% static 'docs/js/list.js' %}"></script>
{% endblock %}

{% block columns %}
    <th class="text-md-center" style="width:3%"></th>
    <th class="text-md-center" style="width:11%">Código</th>
    <th class="text-md-center" style="width:26%">Descripción</th>
    <th class="text-md-center" style="width:4%">Versión</th>
    <th class="text-md-center" style="width:10%">Tipo</th>
    <th class="text-md-center" style="width:7%">Doc</th>
    <th class="text-md-center" style="width:7%">Anexos</th>
    <th class="text-md-center" style="width:7%">Estado</th>
    <th class="text-md-center" style="width:12%">Proceso</th>
    <th class="text-md-center" style="width:10%">Acciones</th>
{% endblock %}

{% block rows %}

{% endblock %}

{% block javascript %}


{% endblock %}

bpmdoc/core/erp/templates/docs/list_created.html
{% extends 'list.html' %}
{% load static %}

{% block head_list %}
    <script src="{% static 'docs/js/list_created.js' %}"></script>
{% endblock %}

{% block columns %}
    <th class="text-md-center" style="width:5%">+Info</th>
    <th class="text-md-center" style="width:10%">Código</th>
    <th class="text-md-center" style="width:28%">Descripción</th>
    <th class="text-md-center" style="width:10%">Tipo</th>
    <th class="text-md-center" style="width:10%">Ver Doc</th>
    <th class="text-md-center" style="width:12%">Estado</th>
    <th class="text-md-center" style="width:20%">Observaciones</th>
    <th class="text-md-center" style="width:5%">Ajustar Enviar</th>
{% endblock %}

{% block rows %}

{% endblock %}

{% block javascript %}


{% endblock %}

bpmdoc/core/erp/templates/docs/list_gestion.html
{% extends 'list.html' %}
{% load static %}

{% block head_list %}
    <script src="{% static 'docs/js/list_gestion.js' %}"></script>
{% endblock %}

{% block columns %}
    <th class="text-md-center" style="width:3%">+Info</th>
    <th class="text-md-center" style="width:12%">Código</th>
    <th class="text-md-center" style="width:32%">Descripción</th>
    <th class="text-md-center" style="width:5%">Versión</th>
    <th class="text-md-center" style="width:10%">Tipo</th>
    <th class="text-md-center" style="width:12%">Ver Doc</th>
    <th class="text-md-center" style="width:7%">Estado</th>
    <th class="text-md-center" style="width:12%">Proceso</th>
    <th class="text-md-center" style="width:10%">Cambios</th>
{% endblock %}

{% block rows %}

{% endblock %}

{% block javascript %}


{% endblock %}

bpmdoc/core/erp/templates/docs/list_review.html
{% extends 'list.html' %}
{% load static %}

{% block head_list %}
    <script src="{% static 'docs/js/list_review.js' %}"></script>
{% endblock %}

{% block columns %}
    <th class="text-md-center" style="width:12%">Código</th>
    <th class="text-md-center" style="width:32%">Descripción</th>
    <th class="text-md-center" style="width:5%">Versión</th>
    <th class="text-md-center" style="width:10%">Tipo</th>
    <th class="text-md-center" style="width:9%">Ver Doc</th>
    <th class="text-md-center" style="width:7%">Estado</th>
    <th class="text-md-center" style="width:12%">Proceso</th>
    <th class="text-md-center" style="width:8%">Aprobar Documento</th>
    <th class="text-md-center" style="width:8%">Devolver Documento</th>
{% endblock %}

{% block rows %}

{% endblock %}


{% block javascript %}



{% endblock %}

bpmdoc/core/erp/templates/docs/listconsulta.html
{% extends 'list.html' %}
{% load static %}

{% block head_list %}
    <script src="{% static 'docs/js/listconsulta.js' %}"></script>
{% endblock %}

{% block columns %}
    <th class="text-md-center" style="width:3%">+Info</th>
    <th class="text-md-center" style="width:12%">Código</th>
    <th class="text-md-center" style="width:34%">Descripción</th>
    <th class="text-md-center" style="width:5%">Versión</th>
    <th class="text-md-center" style="width:12%">Tipo</th>
    <th class="text-md-center" style="width:8%">Ver Doc</th>
    <th class="text-md-center" style="width:7%">Estado</th>
    <th class="text-md-center" style="width:12%">Proceso</th>
{% endblock %}

{% block rows %}

{% endblock %}

{% block javascript %}

{% endblock %}