bpmdoc/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView
from core.login.views import *
from config import settings as setting
from django.conf.urls.static import static

urlpatterns = [
    path ("", IndexView.as_view(), name='index'),
    path ("login/", include('core.login.urls')),
    path ("admin/", admin.site.urls),
    path ("erp/", include ('core.erp.urls')),
    path ("user/", include ('core.user.urls')),
]

if setting.DEBUG:
    urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

bpmdoc/core/user/urls.py
from django.urls import path
from core.user.views import *

app_name = 'user'

urlpatterns = [
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('profile_ver/', UserProfileConsultView.as_view(), name='user_profile_ver'),
    path('edit/password/', UserChangePasswordView.as_view(), name='change_password'),
    path('register/', registerview, name='account_create')
]

bpmdoc/core/homepage/models.py
from django.db import models

# Create your models here.

bpmdoc/core/homepage/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

class SinpermisosView(TemplateView):
    template_name = 'sinpermisos.html'

bpmdoc/core/homepage/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/favicon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    BPM Pro
  </title>
  <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <!-- CSS Files -->
  <link href="{% static 'css/material-kit.css' %}" rel="stylesheet" />
    <style type="text/css">
        .navbar-color-on-scroll {
        }
    </style>
</head>

<body class="landing-page sidebar-collapse">
  <nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top navbar-expand-lg" color-on-scroll="100" id="sectionsNav">
    <div class="container">
      <div class="navbar-translate">
          <div class="logo">
              <img src="{% static 'img/bpm_pro_sh.png' %}" width="250" height="100%" viewBox="0 0 175 45">
          </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}"><h5><b>INICIAR SESION</b></h5></a>
                </li>
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'user:account_create' %}"><h5>CREAR CUENTA</h5></a>#}
{#                </li>#}
            </ul>
        </div>
    </div>
  </nav>


  <div class="page-header header-filter" data-parallax="true" style="background-image: url('{% static 'img/gmp1.jpg' %}')">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h2 class="title">Software para BPM</h2>
            <h4>Sistema Documental para <b>BPM</b> y <b>Batch Record</b> en un solo lugar, maneje electrónicamente todos sus documentos y registros de manufactura y minimize el uso del papel.</h4>
          <br>
          <a href="http://www.cieltechno.com/contacto/" target="_blank" class="btn btn-danger btn-raised btn-lg">
              <b>Contactanos y Solicita tu Demo de 30 días gratis</b>
          </a>
            <div>
              <a><i class="material-icons">mail</i> Email: ventas@cieltechno.com</a>
            </div>
            <div>
               <a><i class="material-icons">phone</i> Celular o Whatsapp: +57 316 6231887</a>
            </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="section text-center">
        <div class="row">
          <div class="col-md-8 ml-auto mr-auto">
            <h2 class="title">Caracteristicas</h2>
            <h5 class="description">Software de bajo de costo para la gestión documental de Buenas Practicas de Manufactura (BPM), ideal para Pymes del sector Cosmetico, Farmacéutico, Fitoterapéutico, Nutracéutico y Alimentario</h5>
              <h5 class="description">Con nuestro Batch Record Electronico, disminuya sustentablemente el uso de papel para el registro de lotes, disminuya costos y ahorre espacio de archivo.</h5>
          </div>
        </div>
{#        <div class="features">#}
{#          <div class="row">#}
{#            <div class="col-md-4">#}
{#              <div class="info">#}
{#                <div class="icon icon-info">#}
{#                  <i class="material-icons">chat</i>#}
{#                </div>#}
{#                <h4 class="info-title">Free Chat</h4>#}
{#                <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>#}
{#              </div>#}
{#            </div>#}
{#            <div class="col-md-4">#}
{#              <div class="info">#}
{#                <div class="icon icon-success">#}
{#                  <i class="material-icons">verified_user</i>#}
{#                </div>#}
{#                <h4 class="info-title">Verified Users</h4>#}
{#                <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>#}
{#              </div>#}
{#            </div>#}
{#            <div class="col-md-4">#}
{#              <div class="info">#}
{#                <div class="icon icon-danger">#}
{#                  <i class="material-icons">fingerprint</i>#}
{#                </div>#}
{#                <h4 class="info-title">Fingerprint</h4>#}
{#                <p>Divide details about your product or agency work into parts. Write a few lines about each one. A paragraph describing a feature will be enough.</p>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
      </div>
{#      <div class="section text-center">#}
{#        <h2 class="title">Here is our team</h2>#}
{#        <div class="team">#}
{#          <div class="row">#}
{#            <div class="col-md-4">#}
{#              <div class="team-player">#}
{#                <div class="card card-plain">#}
{#                  <div class="col-md-6 ml-auto mr-auto">#}
{#                    <img src="{% static 'img/faces/avatar.jpg' %}" alt="Thumbnail Image" class="img-raised rounded-circle img-fluid">#}
{#                  </div>#}
{#                  <h4 class="card-title">Gigi Hadid#}
{#                    <br>#}
{#                    <small class="card-description text-muted">Model</small>#}
{#                  </h4>#}
{#                  <div class="card-body">#}
{#                    <p class="card-description">You can write here details about one of your team members. You can give more details about what they do. Feel free to add some#}
{#                      <a href="#">links</a> for people to be able to follow them outside the site.</p>#}
{#                  </div>#}
{#                  <div class="card-footer justify-content-center">#}
{#                    <a href="#pablo" class="btn btn-link btn-just-icon"><i class="fa fa-twitter"></i></a>#}
{#                    <a href="#pablo" class="btn btn-link btn-just-icon"><i class="fa fa-instagram"></i></a>#}
{#                    <a href="#pablo" class="btn btn-link btn-just-icon"><i class="fa fa-facebook-square"></i></a>#}
{#                  </div>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#            <div class="col-md-4">#}
{#              <div class="team-player">#}
{#                <div class="card card-plain">#}
{#                  <div class="col-md-6 ml-auto mr-auto">#}
{#                    <img src="{% static 'img/faces/christian.jpg' %}" alt="Thumbnail Image" class="img-raised rounded-circle img-fluid">#}
{#                  </div>#}
{#                  <h4 class="card-title">Christian Louboutin#}
{#                    <br>#}
{#                    <small class="card-description text-muted">Designer</small>#}
{#                  </h4>#}
{#                  <div class="card-body">#}
{#                    <p class="card-description">You can write here details about one of your team members. You can give more details about what they do. Feel free to add some#}
{#                      <a href="#">links</a> for people to be able to follow them outside the site.</p>#}
{#                  </div>#}
{#                  <div class="card-footer justify-content-center">#}
{#                    <a href="#pablo" class="btn btn-link btn-just-icon"><i class="fa fa-twitter"></i></a>#}
{#                    <a href="#pablo" class="btn btn-link btn-just-icon"><i class="fa fa-linkedin"></i></a>#}
{#                  </div>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#            <div class="col-md-4">#}
{#              <div class="team-player">#}
{#                <div class="card card-plain">#}
{#                  <div class="col-md-6 ml-auto mr-auto">#}
{#                    <img src="{% static 'img/faces/kendall.jpg' %}" alt="Thumbnail Image" class="img-raised rounded-circle img-fluid">#}
{#                  </div>#}
{#                  <h4 class="card-title">Kendall Jenner#}
{#                    <br>#}
{#                    <small class="card-description text-muted">Model</small>#}
{#                  </h4>#}
{#                  <div class="card-body">#}
{#                    <p class="card-description">You can write here details about one of your team members. You can give more details about what they do. Feel free to add some#}
{#                      <a href="#">links</a> for people to be able to follow them outside the site.</p>#}
{#                  </div>#}
{#                  <div class="card-footer justify-content-center">#}
{#                    <a href="#pablo" class="btn btn-link btn-just-icon"><i class="fa fa-twitter"></i></a>#}
{#                    <a href="#pablo" class="btn btn-link btn-just-icon"><i class="fa fa-instagram"></i></a>#}
{#                    <a href="#pablo" class="btn btn-link btn-just-icon"><i class="fa fa-facebook-square"></i></a>#}
{#                  </div>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
      <div class="section section-contacts">
        <div class="row">
          <div class="col-md-8 ml-auto mr-auto">
            <h2 class="text-center title">Contacténos</h2>
            <h4 class="text-center description">Solicite su Demo de 30 días, y viva a un click de la mejor experiencia en el sistema de gestión documental para Pymes </h4>
            <div>
              <a><i class="material-icons">mail</i>  Email: ventas@cieltechno.com</a>
            </div>
            <div>
               <a><i class="material-icons">phone</i>  Celular o Whatsapp: +57 316 6231887</a>
            </div>
{#            <form class="contact-form">#}
{#              <div class="row">#}
{#                <div class="col-md-6">#}
{#                  <div class="form-group">#}
{#                    <label class="bmd-label-floating">Your Name</label>#}
{#                    <input type="email" class="form-control">#}
{#                  </div>#}
{#                </div>#}
{#                <div class="col-md-6">#}
{#                  <div class="form-group">#}
{#                    <label class="bmd-label-floating">Your Email</label>#}
{#                    <input type="email" class="form-control">#}
{#                  </div>#}
{#                </div>#}
{#              </div>#}
{#              <div class="form-group">#}
{#                <label for="exampleMessage" class="bmd-label-floating">Your Message</label>#}
{#                <textarea type="email" class="form-control" rows="4" id="exampleMessage"></textarea>#}
{#              </div>#}
{#              <div class="row">#}
{#                <div class="col-md-4 ml-auto mr-auto text-center">#}
{#                  <button class="btn btn-primary btn-raised">#}
{#                    Send Message#}
{#                  </button>#}
{#                </div>#}
{#              </div>#}
{#            </form>#}
          </div>
        </div>
      </div>
    </div>
  </div>
  <footer class="footer footer-default">
    <div class="container">
{#      <nav class="float-left">#}
{#        <ul>#}
{#          <li>#}
{#            <a href="https://www.creative-tim.com/">#}
{#              Creative Tim#}
{#            </a>#}
{#          </li>#}
{#          <li>#}
{#            <a href="https://www.creative-tim.com/presentation">#}
{#              About Us#}
{#            </a>#}
{#          </li>#}
{#          <li>#}
{#            <a href="https://www.creative-tim.com/blog">#}
{#              Blog#}
{#            </a>#}
{#          </li>#}
{#          <li>#}
{#            <a href="https://www.creative-tim.com/license">#}
{#              Licenses#}
{#            </a>#}
{#          </li>#}
{#        </ul>#}
{#      </nav>#}
      <div class="copyright float-right">
        &copy;
        <script>
          document.write(new Date().getFullYear())
        </script>. Todos los derechos reservados. Un producto de
        <a href="http://www.cieltechno.com/" target="_blank">CielTechno SAS</a>.
      </div>
    </div>
  </footer>
  <!--   Core JS Files   -->
  <script src="{% static 'js/core/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/bootstrap-material-design.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/plugins/moment.min.js' %}"></script>
  <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
  <script src="{% static 'js/plugins/bootstrap-datetimepicker.js' %}" type="text/javascript"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
  <!--  Google Maps Plugin    -->
  <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'js/material-kit.js.map' %}" type="text/javascript"></script>
</body>

</html>