bpmdoc/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView
from core.login.views import *
from config import settings as setting
from django.conf.urls.static import static

urlpatterns = [
    path ("", IndexView.as_view(), name='index'),
    path ("login/", include('core.login.urls')),
    path ("admin/", admin.site.urls),
    path ("erp/", include ('core.erp.urls')),
    path ("user/", include ('core.user.urls')),
]

if setting.DEBUG:
    urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

bpmdoc/core/erp/urls.py
from django.urls import path

from core.erp.views.changes.views import *
from core.erp.views.inicio.views import *
from core.erp.views.process.views import *
from core.erp.views.typedoc.views import *
from core.erp.views.docs.views import *
from core.homepage.views import SinpermisosView

# url media files
from django.conf import settings
from django.conf.urls.static import static


app_name = 'erp'

urlpatterns = [
    # Tipos de documento
    path('typedoc/list/', TypedocListView.as_view(), name='typedoc_list'),
    path("typedoc/add/", TypeCreateView.as_view(), name='type_create'),
    path('typedoc/update/<int:pk>/', TypeUpdateView.as_view(), name='type_update'),
    path('typedoc/delete/<int:pk>/', TypeDeleteView.as_view(), name='type_delete'),
    path('typedoc/form/', TypeFormView.as_view(), name='type_form'),

    # Documentos
    path('docs/list/', DocListView.as_view(), name='docs_list'),
    path('docs/review_list/', DocRevListView.as_view(), name='docs_review_list'),
    path('docs/approve_list/', DocAproListView.as_view(), name='docs_aprove_list'),
    path('docs/created_list/', DocCreatedListView.as_view(), name='docs_created_list'),
    path('docs/gestion_list/', DocGestListView.as_view(), name='docs_gest_list'),
    path('docs/adjust_update/<int:pk>/', DocAdjustUpdateView.as_view(), name='docs_adjust_update'),
    path('docs/review_update/<int:pk>/', DocRevUpdateView.as_view(), name='docs_review_update'),
    path('docs/approve_update/<int:pk>/', DocAproUpdateView.as_view(), name='docs_aprove_update'),
    path('docs/devolut_update/<int:pk>/', DocDevUpdateView.as_view(), name='docs_devolut_update'),
    path('docs/consulta/', ConsulDocListView.as_view(), name='consultdocs_list'),
    path('docs/add/', DocCreateView.as_view(), name='docs_create'),
    path('docs/update/<int:pk>/', DocUpdateView.as_view(), name='docs_update'),
    path('docs/delete/<int:pk>/', DocDeleteView.as_view(), name='docs_delete'),
    path('docs/detail/<int:pk>', DocsDetailView.as_view(), name='docs_detail'),
    path('docs/form/', DocFormView.as_view(), name='docs_form'),
    path('docs/listado_maestros_docs/', ReportDocsExcel.as_view(), name='list_master_docs'),

    # Procesos
    path('process/list/', ProcessListView.as_view(), name='process_list'),
    path('process/add/', ProcessCreateView.as_view(), name='process_create'),
    path('process/update/<int:pk>/', ProcessUpdateView.as_view(), name='process_update'),
    path('process/delete/<int:pk>/', ProcessDeleteView.as_view(), name='process_delete'),
    path('process/form/', ProcessFormView.as_view(), name='process_form'),

    # Cambios de documentos/ Control de Cambios
    path('changes/update/<int:id_change>/', document_change, name='changes_control'),

    # Inicio
    path('inicio/', InicioView.as_view(), name='inicio'),
    path('inicio/sinpermisos/', SinpermisosView.as_view(), name='sinpermisos'),

]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

bpmdoc/core/user/urls.py
from django.urls import path
from core.user.views import *

app_name = 'user'

urlpatterns = [
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('profile_ver/', UserProfileConsultView.as_view(), name='user_profile_ver'),
    path('edit/password/', UserChangePasswordView.as_view(), name='change_password'),
    path('register/', registerview, name='account_create')
]

bpmdoc/core/erp/models.py
from crum import get_current_user
from django.core.validators import FileExtensionValidator

from django.db import models
from django.forms import model_to_dict
from simple_history.models import HistoricalRecords

from core.models import BaseModel
from djchoices import ChoiceItem, DjangoChoices
from config.settings import MEDIA_URL
from core.user.models import User
from datetime import datetime, timedelta


class Type(BaseModel):
    typedoc = models.CharField(max_length=60, verbose_name='Descripción', unique=True)
    codetype = models.CharField(max_length=10, verbose_name='Código', unique=True)
    validity = models.IntegerField(verbose_name='Años de Vigencia')
    history = HistoricalRecords(custom_model_name=lambda x:f'Audit_{x}')

    def __str__(self):
        return self.typedoc

    def toJSON(self):
        item = model_to_dict(self)
        item['user_creation'] = self.user_creation.__str__()
        item['user_updated'] = self.user_updated.__str__()
        item['date_creation'] = self.date_creation.strftime('%Y-%m-%d')
        item['date_updated'] = self.date_updated.strftime('%Y-%m-%d')
        return item

    class Meta:
        db_table = 'Tipo_Documento'
        verbose_name = 'Tipo de Documento'
        verbose_name_plural = 'Tipos de Documentos'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None, *args, **kwargs):
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        self.typedoc = self.typedoc.capitalize()
        self.codetype = self.codetype.upper()
        return super(Type, self).save(*args, **kwargs)


class VigenciaDoc(DjangoChoices):
    one_year = ChoiceItem('365', "1 año")
    two_year = ChoiceItem('730', "2 años")
    three_year = ChoiceItem('1095', "3 años")
    four_year = ChoiceItem('1461', "4 años")
    five_year = ChoiceItem('1825', "5 años")


class StatusDoc(DjangoChoices):
    elaboracion = ChoiceItem('En Elaboración', "En Elaboración")
    revision = ChoiceItem("En Revisión", "En Revisión")
    aprobacion = ChoiceItem("En Aprobación", "En Aprobación")
    aprobado = ChoiceItem("Aprobado", "Aprobado")
    vigente = ChoiceItem("Vigente", "Vigente")
    vencido = ChoiceItem("Vencido", "Vencido")
    obsoleto = ChoiceItem("Obsoleto", "Obsoleto")
    prueba = ChoiceItem("En Prueba", "En Prueba")
    anulado = ChoiceItem("Anulado", "Anulado")


class Document(BaseModel):
    code = models.CharField(max_length=15, verbose_name='Código')
    description = models.CharField(max_length=200, verbose_name='Descripción')
    version = models.IntegerField(default=1, verbose_name='Versión N°')
    tipodoc = models.ForeignKey('Type', verbose_name='Tipo de Documento', on_delete=models.CASCADE)
    creator = models.ForeignKey(User, blank=False, verbose_name='Creado por', on_delete=models.CASCADE,
                                related_name='+')
    reviewer = models.ForeignKey(User, blank=False, verbose_name='Revisado por', on_delete=models.CASCADE,
                                 related_name='+')
    owner = models.ForeignKey(User, blank=False, verbose_name='Aprobado por', on_delete=models.CASCADE,
                              related_name='+')
    proceso = models.ForeignKey('Process', verbose_name='Proceso', on_delete=models.CASCADE)
    filepdf = models.FileField(upload_to='docspdf/%Y/%m/%d', max_length=200, blank=True,
                               verbose_name='Documento en PDF', validators=[FileExtensionValidator(['pdf'])])
    fileword = models.FileField(upload_to='docsword/%Y/%m/%d', max_length=200, blank=True,
                                verbose_name='Documento editable', validators=[FileExtensionValidator(['xls', 'xlsx', 'doc', 'docx'])])
    anexo = models.FileField(upload_to='anexos/%Y/%m/%d', max_length=200, blank=True, null=True, verbose_name='Anexo 1')
    anexo_dos = models.FileField(upload_to='anexos_dos/%Y/%m/%d', max_length=200, blank=True, null=True,
                                 verbose_name='Anexo 2')
    status = models.CharField(max_length=100, default='En Elaboración', choices=StatusDoc.choices,
                              verbose_name='Estado')
    changes = models.CharField(max_length=1000, null=True, blank=True, verbose_name='Cambios Realizados')
    justification = models.CharField(max_length=1000, null=True, blank=True, verbose_name='Justificación del Cambio')
    numberchange = models.IntegerField(unique=True, null=True, blank=True, verbose_name='N° de Documento')
    review = models.BooleanField(default=False, null=True, blank=True, verbose_name='Aprobar Revisión')
    approval = models.BooleanField(default=False, null=True, blank=True, verbose_name='Aprobar Documento')
    date_revised = models.DateField(default=None, blank=True, null=True, verbose_name='Fecha de Revisado')
    date_approved = models.DateField(default=None, blank=True, null=True, verbose_name='Fecha de Aprobado')
    time_vigencia = models.CharField(max_length=10, choices=VigenciaDoc.choices, blank=True, null=True,
                                     verbose_name='Tiempo de Vigencia')
    date_vigencia = models.DateField(default=None, blank=True, null=True, verbose_name='Vencimiento de Documento')
    date_alert_exp = models.DateField(default=None, blank=True, null=True, verbose_name='Fecha Notificacion Proximo a Vencer')
    comment_review = models.CharField(max_length=250, null=True, blank=True, verbose_name='Observaciones Revisión')
    comment_aprove = models.CharField(max_length=250, null=True, blank=True, verbose_name='Observaciones Aprobación')
    empresa = models.CharField(max_length=50, default='Laboratorios H&B SAS', verbose_name='Compañia', null=True, blank=True)
    history = HistoricalRecords(custom_model_name=lambda x:f'Audit_{x}')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.last_name = None
        self.first_name = None

    def __str__(self):
        return self.description

    def toJSON(self):
        item = model_to_dict(self)
        item['tipodoc'] = self.tipodoc.toJSON()
        item['proceso'] = self.proceso.toJSON()
        item['filepdf'] = self.get_pdf()
        item['fileword'] = self.get_status_display()
        item['anexo'] = self.get_status_anexo()
        item['anexo_dos'] = self.get_status_anexo_dos()
        item["date_vigencia"] = None if self.date_vigencia is None else self.date_vigencia.strftime('%Y-%m-%d')
        item['date_alert_exp'] = None if self.date_alert_exp is None else self.date_alert_exp.strftime('%Y-%m-%d')
        item['date_creation'] = self.date_creation.strftime('%Y-%m-%d')
        item['date_updated'] = self.date_updated.strftime('%Y-%m-%d')
        item["date_revised"] = None if self.date_revised is None else self.date_revised.strftime('%Y-%m-%d')
        item['date_approved'] = None if self.date_approved is None else self.date_approved.strftime('%Y-%m-%d')
        return item

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None, *args, **kwargs):
        if self.date_approved is not None:
            diasv = self.time_vigencia
            intdiasv = int(diasv)
            self.date_vigencia = datetime.now() + timedelta(days=intdiasv)
        if self.date_vigencia is not None:
            self.date_alert_exp = self.date_vigencia - timedelta(days=30)
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        super(Document, self).save()
        self.description = self.description.capitalize()
        self.code = self.code.upper()
        return super(Document, self).save(*args, **kwargs)

    def get_pdf(self):
        if self.filepdf:
            return '{}{}'.format(MEDIA_URL, self.filepdf)
        return ''

    def get_status_display(self):
        if self.fileword:
            return '{}{}'.format(MEDIA_URL, self.fileword)
        return ''

    def get_status_anexo(self):
        if self.anexo:
            return '{}{}'.format(MEDIA_URL, self.anexo)
        return ''

    def get_status_anexo_dos(self):
        if self.anexo_dos:
            return '{}{}'.format(MEDIA_URL, self.anexo_dos)
        return ''

    class Meta:
        verbose_name = 'Documento'
        verbose_name_plural = 'Documentos'
        db_table = 'Documentos'
        ordering = ['-date_updated']


class Process(BaseModel):
    process = models.CharField(max_length=60, verbose_name='Descripción', unique=True)
    codeprocess = models.CharField(max_length=10, verbose_name='Código', unique=True)
    leader = models.ForeignKey(User, blank=True, verbose_name='Líder de Proceso', on_delete=models.CASCADE)
    history = HistoricalRecords(custom_model_name=lambda x:f'Audit_{x}')

    def __str__(self):
        return self.process

    def toJSON(self):
        item = model_to_dict(self)
        item['leader'] = self.leader.tojson()
        return item

    class Meta:
        db_table = 'Proceso'
        verbose_name = 'Proceso'
        verbose_name_plural = 'Procesos'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None, *args, **kwargs):
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        self.process = self.process.capitalize()
        self.codeprocess = self.codeprocess.upper()
        return super(Process, self).save(*args, **kwargs)

bpmdoc/core/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import model_to_dict
from simple_history.models import HistoricalRecords


class User(AbstractUser):
    cedula = models.CharField(max_length=15, null=True, blank=True, unique=False, verbose_name='Cédula')
    cargo = models.CharField(max_length=50, null=True, blank=True, verbose_name='Cargo')
    cellphone = models.CharField(max_length=10, null=True, blank=True, verbose_name='N° Celular')
    history = HistoricalRecords(custom_model_name=lambda x:f'Audit_{x}')

    def __str__(self):
        return f'{self.get_full_name()}, {self.cargo}'

    def is_active_display(self):
        if self.is_active is True:
            return 'Activo'
        return 'Inactivo'

    def tojson(self):
        item = model_to_dict(self, exclude=['password', 'user_permissions'])
        if self.last_login:
            item['last_login'] = self.date_joined.strftime('%Y-%m-%d %H:%M')
        item['date_joined'] = self.date_joined.strftime('%Y-%m-%d')
        item['full_name'] = self.get_full_name()
        item['is_active'] = self.is_active_display()
        item['groups'] = [{'id': g.id, 'name': g.name} for g in self.groups.all()]
        return item

bpmdoc/core/erp/views/inicio/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from core.erp.models import Document


class InicioView(LoginRequiredMixin, TemplateView):
    template_name = 'inicio.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'panel del administrador'
        context['tittle'] = 'Inicio'
        context['entity'] = 'Inicio'
        context['count_vencido'] = Document.objects.filter(status='Vencido').filter(
            owner=self.request.user).count()
        context['count_aprobar'] = Document.objects.filter(status='En Aprobación').filter(
            owner=self.request.user).count()
        context['count_elaboracion'] = Document.objects.filter(status='En Elaboración').filter(
            creator=self.request.user).count()
        context['count_revisar'] = Document.objects.filter(status='En Revisión').filter(
            reviewer=self.request.user).count()
        context['count_por_vencer'] = Document.objects.filter(status='Vigente').filter(
            date_alert_exp__lte=datetime.now()).filter(owner=self.request.user).count()
        context['count_total'] = context['count_aprobar'] + context['count_vencido'] + context['count_elaboracion'] + \
                                 context['count_revisar'] + context['count_por_vencer']
        return context

bpmdoc/templates/footer.html
<div>
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Derechos Reservados&copy; BPMPro v1.0.0 2020. Un producto de CielTechno SAS</span>
        </div>
    </div>
</footer>

bpmdoc/templates/header.html
{% load static  %}

      <!-- Main Content -->
<div id="content" xmlns="http://www.w3.org/1999/html">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Informacion Compañia - Cliente -->
            <div class="input-group">
              <a href="">
                  <img src="{% static 'img/logo_hb.jpg' %}" alt="" style="max-width:40%;width:auto;height:auto">
              </a>
            </div>

            <div class="col-sm-4">
                <h5 class="m-0 text-dark" style="text-align: right"><small>{{ request.user.get_full_name }}</small></h5>
            </div>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>


            </li>

            <!-- Central Alertas -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Contador total Alertas -->
                  {% if count_total > 0 %}
                      <span class="badge badge-danger badge-counter">{{ count_total }}</span>
                  {% endif %}
              </a>
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Centro de Alertas
                </h6>
                {% if user.is_authenticated %}
                  {% if perms.erp.change_document %}
                       {% if count_aprobar > 0 %}
                            <a class="dropdown-item d-flex align-items-center" href="{% url 'erp:docs_aprove_list' %}">
                                <div class="mr-3">
                                <div class="icon-circle bg-primary">
                                  <i class="fas fa-file-alt text-white"></i>
                                </div>
                              </div>
                              <div>
                                <span class="font-weight-bold">Documentos por Aprobar</span>
                                <span class="badge badge-danger badge-counter">{{ count_aprobar }}</span>
                              </div>
                            </a>
                       {% endif %}
                       {% if count_revisar > 0 %}
                            <a class="dropdown-item d-flex align-items-center" href="{% url 'erp:docs_review_list' %}">
                              <div class="mr-3">
                                <div class="icon-circle bg-success">
                                  <i class="fas fa-file-alt text-white"></i>
                                </div>
                              </div>
                              <div>
                                <span class="font-weight-bold">Documentos por Revisar</span>
                                <span class="badge badge-danger badge-counter">{{ count_revisar }}</span>
                              </div>
                            </a>
                        {% endif %}
                       {% if count_elaboracion > 0 %}
                            <a class="dropdown-item d-flex align-items-center" href="{% url 'erp:docs_created_list' %}">
                              <div class="mr-3">
                                <div class="icon-circle bg-warning">
                                  <i class="fas fa-file-alt text-white"></i>
                                </div>
                              </div>
                              <div>
                                <span class="font-weight-bold">Documentos en Elaboración</span>
                                <span class="badge badge-danger badge-counter">{{ count_elaboracion }}</span>
                              </div>
                            </a>
                        {% endif %}
                       {% if count_vencido > 0 %}
                            <a class="dropdown-item d-flex align-items-center" href="{% url 'erp:docs_gest_list' %}">
                              <div class="mr-3">
                                <div class="icon-circle bg-danger">
                                  <i class="fas fa-exclamation-triangle text-white"></i>
                                </div>
                              </div>
                              <div>
                                <span class="font-weight-bold">Documentos Vencidos</span>
                                <span class="badge badge-danger badge-counter">{{ count_vencido }}</span>
                              </div>
                            </a>
                        {% endif %}
                       {% if count_por_vencer > 0 %}
                            <a class="dropdown-item d-flex align-items-center" href="{% url 'erp:docs_gest_list' %}">
                              <div class="mr-3">
                                <div class="icon-circle bg-warning">
                                  <i class="fas fa-exclamation-triangle text-white"></i>
                                </div>
                              </div>
                              <div>
                                <span class="font-weight-bold">Documentos a Vencer</span>
                                <span class="badge badge-danger badge-counter">{{ count_por_vencer }}</span>
                              </div>
                            </a>
                        {% endif %}
                  {% endif %}
                {% endif %}
              </div>
            </li>


            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.username }}</span>
                <img class="img-profile rounded-circle" alt="perfil" src="{% static 'lib/startbootstrap-sb-admin-2/img/user-02.svg' %}">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'user:user_profile_ver' %}">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Mi Perfil
                </a>
                <a class="dropdown-item" href="{% url 'user:change_password' %}">
                  <i class="fas fa-key fa-sm fa-fw mr-2 text-gray-400"></i>
                  Cambiar Contraseña
                </a>
                <a class="dropdown-item">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Tipo de Usuario:
                    {% for g in request.user.groups.all %}
                        {{ g.name }}
                    {% endfor %}
                </a>
                <a class="dropdown-item">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Ultimo acceso: {{ request.user.last_login }}
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  <b>CERRAR SESIÓN</b>
                </a>
              </div>
            </li>

          </ul>

        </nav>

bpmdoc/templates/sidebar.html
{%  load static %}

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- BPMPro -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
        <div class="sidebar-brand-icon rotate-n-15">      
        </div>
          <img src="{% static 'lib/startbootstrap-sb-admin-2/img/logo_bpm6.png' %}" alt="BPM Pro" style="max-width:80%;width:auto;height:auto">
      </a>

      <!-- Inicio -->
      {% url 'erp:inicio' as ini_url %}
      <hr class="sidebar-divider my-0">
      <li class="nav-item {% if ini_url in request.path %} active {% endif %}">
        <a class="nav-link" href="{% url 'erp:inicio' %}">
        <i class="fas fa-home"></i>
          <span>Inicio</span></a>
      </li>
      <hr class="sidebar-divider">
      <div class="sidebar-heading">
        Aseguramiento de la Calidad
      </div>
        <!-- Variables para menú activo 1 -->
        {% url 'erp:typedoc_list' as type %}
        {% url 'erp:process_list' as process %}
        {% url 'erp:docs_list' as docs %}
        {% url 'erp:docs_gest_list' as docgest %}
        {% url 'erp:consultdocs_list' as consult %}
        {% url 'erp:docs_create' as docscreate %}
        {% url 'erp:process_create' as processcreate %}
        {% url 'erp:type_create' as typecreate %}

      <!-- Gestion del sistema documental -->
      <li class="nav-item
        {% if type in request.path or process in request.path or docs in request.path or docgest in request.path or consult in request.path or docscreate in request.path or processcreate in request.path or typecreate in request.path%}
        active
        {% endif %}">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-folder"></i>
          <span>Gestión Documental</span>
        </a>
        <div id="collapseOne" class="collapse {% if type in request.path or process in request.path or docs in request.path or docgest in request.path or consult in request.path or docscreate in request.path or processcreate in request.path or typecreate in request.path %}
        show
        {% endif %} " aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            {% if perms.erp.view_type %}
                <a class="collapse-item {% if type in request.path or typecreate in request.path %} active
                {% endif %}" href="{% url 'erp:typedoc_list' %}">Tipos de Documento</a>
            {% endif %}
            {% if perms.erp.view_process %}
                <a class="collapse-item {% if process in request.path or processcreate in request.path %} active
                {% endif %}" href="{% url 'erp:process_list' %}">Procesos</a>
            {% endif %}
            {% if perms.erp.add_document %}
                <a class="collapse-item {% if docs in request.path or docscreate in request.path %} active
                {% endif %}" href="{% url 'erp:docs_list' %}">Maestro de Documentos</a>
            {% endif %}
            {% if perms.erp.change_document %}
                <!-- Consulta de documentos usuarios Gestores Doc, revisores y aprobadores-->
                <a class="collapse-item {% if docgest in request.path %} active
                {% endif %}" href="{% url 'erp:docs_gest_list' %}">Listado de Documentos</a>
            {% endif %}
            {% if perms.erp.view_document %}
                <a class="collapse-item {% if consult in request.path %} active
                {% endif %}" href="{% url 'erp:consultdocs_list' %}">Consulta de Documentos</a>
            {% endif %}
          </div>
        </div>
      </li>
      <!-- Menú Administración del sistema -->
      <hr class="sidebar-divider d-none d-md-block">
      {% if perms.user.view_user %}
      <div class="sidebar-heading">
        Administración del sistema
      </div>
          <!-- Variables para menu activo 2-->
          {% url 'user:user_list' as user_url %}
          {% url 'user:user_create' as crearuser_url %}

        <!-- Administración de Usuarios -->
      <li class="nav-item {% if user_url in request.path or crearuser_url in request.path %} active
      {% endif %} ">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-users-cog"></i>
          <span>Gestión de Usuarios</span>
        </a>
        <div id="collapseThree" class="collapse {% if user_url in request.path or crearuser_url in request.path %} show
        {% endif %} " aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item {% if user_url in request.path %} active {% endif %}" href="{% url 'user:user_list' %}">Listado de Usuarios</a>
            <a class="collapse-item {% if crearuser_url in request.path %} active {% endif %}" href="{% url 'user:user_create' %}">Creación de Usuarios</a>
          </div>
        </div>
      </li>
      {% endif %}
      <!-- Sidebar compacto-->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>